### ISSUE TITLE
[sideToolbarPlugin] : 'Cannot read property 'getBoundingClientRect' of undefined'

### ISSUE THREAD

**Issue by michaelspeed** [draft-js-plugins/draft-js-plugins#1024]
i am constantly getting this error and the side toolbar is also not showing up -

    import React, { Component } from 'react'
    import Editor, { createEditorStateWithText } from 'draft-js-plugins-editor'
    import createSideToolbarPlugin from 'draft-js-side-toolbar-plugin'
    import 'draft-js-side-toolbar-plugin/lib/plugin.css'

    const sideToolbarPlugin = createSideToolbarPlugin()
    const { SideToolbar } = sideToolbarPlugin
    const plugins = [sideToolbarPlugin]
    const text = 'Write Something ...'

    class Creator extends Component { 
         state = {
               editorState: createEditorStateWithText(text)
         }

     onChange = (editorState) => { 
          this.setState({
                 editorState
          })
      }

      focus = () => { 
         this.main.focus()
     }

     render() { 
        console.log(this.state)
        return (
          <div style={{ marginTop: 20, minHeight: '300px' }} onClick={this.focus}>
            <div>
               <Editor
                  editorState={this.state.editorState}
                  onChange={this.onChange}
                   plugins={plugins}
                    ref={(element) => { this.main = element}}  
               />
              <SideToolbar/>  
           </div>
       </div>
     )
    }
    }
     export default Creator

`"draft-js": "^0.10.5",
    "draft-js-plugins-editor": "^2.0.4",
    "draft-js-side-toolbar-plugin": "^2.0.1",`

error - 
`TypeError: Cannot read property 'getBoundingClientRect' of undefined`

**Comment by iamawwsome** [comment]
I had the same issues.

Try downgrading your draft-js to 0.10.1. That's how I got the draft-js-side-toolbar-plugin to work.

`npm install draft-js@0.10.1 --save`

**Comment by michaelspeed** [comment]
downgrading does not work, its still the same error

**Comment by Gabiras12** [comment]
Also getting this error here. Any clue?

**Comment by jamesbillinger** [comment]
Looks like this is where the error is occurring.
https://github.com/draft-js-plugins/draft-js-plugins/blob/656079cf2bbda71930022013f6c3e521b12667d8/draft-js-side-toolbar-plugin/src/components/Toolbar/index.js#L40

DraftEditor.refs.editor no longer exists.  If I change the line in question to this it works.

> const editor = this.props.store.getItem('getEditorRef')().editor;

I haven't submitted a PR because I'm not totally sure if this is a permanent change to draft-js.  If so, might want to add something for backward compatibility.  I couldn't find anything in the draft-js changelog.

**Comment by itamarminmed** [comment]
Hey guys. Any news on this?

**Comment by freedomlang** [comment]
I think this is a permanent change ,  because the ref attribute in draft-js-plugins-editor is no longer a string since [cf6653f196c0b23b191b03f968d30eace8e62d4b](https://github.com/draft-js-plugins/draft-js-plugins/commit/cf6653f196c0b23b191b03f968d30eace8e62d4b#diff-2180aea2d91b1762f617f66247191a4c)

**Comment by ram619prasad** [comment]
@iamawwsome I had the same issue. Sidetoolbar did work by downgrading draftsjs to 0.10.1 👍

**Comment by francisrod01** [comment]
+1 the same issue.

**Comment by juliankrispel** [comment]
try version the latest version of the plugins please - it's now fixed
