### ISSUE TITLE
draft-js-mention-plugins: mentionSuggestions is handling up/down arrow keys even when it's inactive

### ISSUE THREAD

**Issue by gnestor** [draft-js-plugins/draft-js-plugins#1026]
## Use-case/Problem

![](https://user-images.githubusercontent.com/1851359/29960622-b4e730e6-8efc-11e7-893e-c5857010d9c6.gif)

This was initially reported in https://github.com/draft-js-plugins/draft-js-plugins/issues/856. I'm running the current master of this repo and still running into this issue. I have looked at the source and I will submit a PR that I think should fix this. I can't reproduce this in [the example](https://codesandbox.io/s/MjG72jX2R) because the mentions don't change in that example, therefore the [mentionSuggestions.componentWillReceiveProps](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L52-L58) is never called, but when it is, it will either open the dropdown or close it based on whether the suggestions have changed or not, which doesn't make sense to me (if the dropdown is open when props change, keep it open, if closed, then keep it closed).

**Comment by davidmfoley** [comment]
I ran into this because I was filtering the suggestions upon render, which makes the equality check on `suggestions` always fail here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L36

(since it is two different references to arrays what happen to have the same items)

Switched over to filtering the suggestions in `onSearchChange`, and storing the result in `state` and got my up and down arrows back.

**Comment by ilya-lopukhin** [comment]
> I ran into this because I was filtering the suggestions upon render, which makes the equality check on `suggestions` always fail here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L36
> 
> (since it is two different references to arrays that happen to have the same items)
> 
> Switched over to filtering the suggestions in `onSearchChange`, and storing the result in `state` and got my up and down arrows back.

I had a similar issue and and based on your workaround i wrapped my suggestions into `useMemo` hook. The problem is gone 🔥
