### ISSUE TITLE
[Mentions] Re-open autocomplete on backspace?

### ISSUE THREAD

**Issue by pklavins** [draft-js-plugins/draft-js-plugins#1037]
Is it possible to do this with the Mentions plugin? Using the [default example](https://www.draft-js-plugins.com/plugin/mention), I can add a name e.g. '@Matthew Russell', but when I backspace (e.g. all the way back to '@M') the autocomplete doesn't re-open. For another example, see Slack's mentioning system; that's what I'm trying to replicate.

**Comment by dem** [comment]
Hi @pklavins 
As i see in your example you have used different styled text while typing name. Mention plugin did not detect mentions in this case, due to bug in detection code.
We have similar problem and fixed it in our fork.

There is opened pull request to handle this problem for draft mention plugin:
https://github.com/draft-js-plugins/draft-js-plugins/pull/1003

**Comment by juliankrispel** [comment]
@dem you’re doing quite a bit of maintenance in this repo - thank you so much! Would love to add you to the team if you’re interested - fancy getting in touch on slack or twitter or wherever for a chat? My email is julian [at] reactrocket.com

**Comment by juliankrispel** [comment]
I’m afraid the mentions plugin can’t support every nuanced use-case - we already have a ton of configuration for it and adding more seems overkill - I’m really sorry
