### ISSUE TITLE
Community-driven DraftJS Plugins

### ISSUE THREAD

**Issue by Hongbo-Miao** [draft-js-plugins/draft-js-plugins#1050]
Hi @nikgraf @bkniffler @juliankrispel!

**DraftJS Plugins** is an awesome package. Thank you soooo much for your work and bringing to us!

Today more and more people start to use it, create issues and pull requests, you might not have enough time to handle all of these. Maybe it is time to think to add more maintainers and let the community drive?

[The Storybook Story](https://medium.com/storybookjs/the-storybook-story-dd3c1ab0d2ce) is big success when they release first community-driven version.

If the current core DraftJS Plugins team can handle it properly, I believe it will help draft-js-plugins grow faster and more popular.

Would like to hear more your thoughts.

Thanks
Hongbo

**Comment by juliankrispel** [comment]
All good points I'm a little overwhelmed tbh and will be making an effort to add more people for help.

Will be thinking about how to best approach this and get back to this. Thanks

**Comment by juliankrispel** [comment]
So for anyone who is interested in participating maintaining draft js plugins here's a doodle to pin down a meeting this week - ideally we'd have them regularly - https://doodle.com/poll/u894g97sscxt3v4f

Looking forward to chatting to you folks on skype <3

**Comment by juliankrispel** [comment]
Sososo:

- We've had 2 meetings so far with much success
- A ton of releases since
- The draft-js-plugins channel on slack is more active then ever
- We're roadmapping upcoming changes (docs, flowtypes, new versions of plugins etc...)

[Here are the minutes from the meeting](https://paper.dropbox.com/doc/draft-js-plugins-maintainers-minutes-zgkupXu49i5wM4soIshgs)

I'm closing this issue for now, but please if you'd like to get involved reach out on the draft-js slack!
