### ISSUE TITLE
[draft-js-mention-plugin] Unknown prop `mentionSuggestionsComponent`

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [draft-js-plugins/draft-js-plugins#1092]
Under mentions, I am using a mentionSuggestionsComponent as listed in the docs - however, this doesn't seem to work as I get an error `Warning: Unknown prop mentionSuggestionsComponent on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

Original documentation: [Draft-js-Plugins: Mentions](https://www.draft-js-plugins.com/plugin/mention)

<img width="555" alt="screen shot 2018-04-29 at 6 38 07 pm" src="https://user-images.githubusercontent.com/13284723/39411663-818c58dc-4bdc-11e8-803d-29ec0fcbf3b6.png">

**Comment by tumetus** [comment]
I think the mentionSuggestionsComponent should be passed to createMentionPlugin() and not for the MentionSuggestions-component. The documentation lists it under the **MentionSuggestions** heading when it should be under the **Configuration Parameters**. So I guess it is under the wrong heading at the docs. Try passing it when you are initialising your mention plugin.
```javascript
this.mentionPlugin = createMentionPlugin({
      mentionSuggestionsComponent: () => { return (<div>Testing Mentions Suggestions</div>); }
});
```
Note that the component passed _must implement the same interface like MentionSuggestions._

**Comment by shankstee** [comment]
@tumetus What do you/the docs mean by: 'Note that the component passed must implement the same interface like MentionSuggestions.' How should this be done? Could you provide an example?

**Comment by tumetus** [comment]
This basically means that it should have the same props as the MentionSuggestion component has because the plugin expects the component passed to mentionSuggestionsComponent to have the same props as the MentionSuggestions component has.

You can see the MentionSuggestions component code here https://github.com/draft-js-plugins/draft-js-plugins/blob/641b53ae721bd8e251eec5a84bf324f240b0c3c6/packages/mention/src/MentionSuggestions/MentionSuggestions.tsx#L69 . Hope this helps!
