### ISSUE TITLE
[draft-js-alignment-plugin] Execute actions after alignment is set

### ISSUE THREAD

**Issue by NeoHub** [draft-js-plugins/draft-js-plugins#1099]
Hey guys,

Is there a way we can capture an "onAlignmentChange" event, so we can execute actions like saving data right after the alignment is set? I was trying to do it from the "onChange" of the draftjs editor, but it fires too many times. Also, if I compare the `editorState` before and after the "onChange" is fired, for some reason the `entityMap` is the same (it always shows the new alignment value). So I don't have a way to know exactly in what moment the alignment changes.

**Comment by juliankrispel** [comment]
@NeoHub no there isn't I'm afraid.

Why do you need just the alignment change? Please explain the use-case to me and I'll see what I can do.

**Comment by NeoHub** [comment]
Sure @juliankrispel. I want to detect that my editorState has changed, so I can save my changes. Usually I do it this way:

```
        const currentContentState = this.state.description.getCurrentContent();
        const newContentState = editorState.getCurrentContent();

        if (currentContentState !== newContentState) {
            // Save changes
        } 
```
So I know that there was an actual change, and not a mere click or a focus. In case an image is aligned, both `currentContentState` and `newContentState` are the same, so I don't have a way to save that. Does it make sense?

**Comment by juliankrispel** [comment]
Ok I had a brief look at this. Basically the alignment is stored inside entity data which is not exposed in ContentState (at least not in the currently distributed version 😢 ) - So that's really what you'd have to compare. It's a very unfortunate design flaw but all entity types are currently still stored in the `DraftEntity` singleton. This is changing in a future draft-js version - I'm just very unsure how long that'll take :/

In the meantime, here's how you'd get the entity data, you'd need to compare that: 

```
const content = editorState.getCurrentContent()
const entities = Object.values(content.entityMap).map(key => content.getEntity(key).toJS());
```
 
One way to fix this would be to use character styles, now, an atomic block isn't strictly a character so it'd be semantically wrong, but it's worth considering to smoothen over the edges of draft-js's current release

**Comment by NeoHub** [comment]
@juliankrispel Thank you, that helped a lot! I achieved to detect those kind of changes comparing the previous `entityMap` with the new one. I had to get them in a different way because `content.entityMap` works only in an `0.11.0-alpha` version of the draftjs library, so I did it converting the `contentState` to raw first and checking the `entityMap` object.

**Comment by juliankrispel** [comment]
@NeoHub you're welcome :+1:
