### ISSUE TITLE
Some Emoji show spaces after them

### ISSUE THREAD

**Issue by Daniel15** [draft-js-plugins/draft-js-plugins#111]
<img src="http://ss.dan.cx/2016/03/chrome_23-22.50.23.png" />

After selecting it then typing "test", there's some space after it:
<img src="http://ss.dan.cx/2016/03/chrome_23-22.50.41.png" />

When I highlight the text, it looks like there's invisible characters there (?):
<img src="http://ss.dan.cx/2016/03/chrome_23-22.51.19.png" />

Chrome, Windows 10.

**Comment by nikgraf** [comment]
thanks for reporting!

Seems like something goes wrong during the unicode conversion. Will look into this tomorrow.

**Comment by Daniel15** [comment]
Just confirmed that this also happens on Mac OS X. The behaviour when selecting the text is different to that on Windows (can't see those invisible characters) but there's still a blank space:

<img width="123" alt="screen shot 2016-03-23 at 11 25 16 pm" src="https://cloud.githubusercontent.com/assets/91933/14010008/8c8025a6-f14e-11e5-9f7d-b930ea62fd53.png">

**Comment by juliankrispel** [comment]
@nikgraf defo something with unicode conversion, I see this when I look at the source:
![image](https://cloud.githubusercontent.com/assets/1188186/14012757/3294b200-f1a8-11e5-9967-0fbddc2f089f.png)

**Comment by juliankrispel** [comment]
So this happened when a unicode consist of surrogate pairs because utf-8 characters can only have a maximum of 6 bytes per character, so what you do instead is combine multiple codepoints. When I first saw this I immediately had to think of @mathiasbynens excellent [talk at DotJS](https://www.youtube.com/watch?v=XD_5xDN7KUA) a few years back :D
