### ISSUE TITLE
Plugins editor is not working correctly in non-english language

### ISSUE THREAD

**Issue by ktjd123** [draft-js-plugins/draft-js-plugins#1137]
when you try to type "안녕하세요" (It's korean)
Its not detected until non-korean char is detected ( ex: space, or alphabet)
I'm not sure this problem is all over other languages but seems like utf-8 problem I guess
Check this please

Thank you I appreciate your work

**Comment by simsim0709** [comment]
Hello, @ktjd123 

It's not actually related to draft-js-plugins, but draft-js which draft-js-plugin depends on.

The current version of draft-js doesn't handle IME keyboard input, well.

You can find out related issues [here](https://github.com/facebook/draft-js/issues)

I will close this, if you think this issue is related into this plugin you can reopen it.

Thanks.
