### ISSUE TITLE
Store an ID for a user, not their name

### ISSUE THREAD

**Issue by thewillk** [draft-js-plugins/draft-js-plugins#1157]
I'm thinking of making a pull-request to add this functionality but would like to get some feedback on if the maintainers think it's a good idea before I spend the time coding it and opening a PR... For all I know there's a piece of functionality I haven't learned about yet that might solve this better.

## Use-case/Problem

- WRT draft-js-mention-plugin, I'd like to be able to display something different to the user than what is actually stored for a mention.
- If a selected user has a name of "Jane Doe" and has an ID of "user12", I'd want the UI (`mentionComponent`) to display "Jane Doe", but if I read the value of the editor content I'd like to be "@user12" (assuming `mentionPrefix = "@"`).
- At the moment, it appears to be set via ``${mentionPrefix}${mention.name}``

Let me know what y'all think about this change.

Whatever happens, I appreciate the work y'all have put into this (and the other) draft js plugins.

**Comment by randolf** [comment]
I think this is a fantastic idea because if the user's English-proper name changes between adding them with an @mention and submitting the form, everything will function as the user expects because their ID will be consistent (assuming, of course, that a user's ID doesn't change).

While you're at it, if there's no option to display the @ symbol in front of the @mention, if you could add that in too that would be great.
