### ISSUE TITLE
Link not recognizing with existing editor content on component load

### ISSUE THREAD

**Issue by shobhit-github** [draft-js-plugins/draft-js-plugins#1231]
Hi there,

I facing an issue that whenever i try to write any link or with copy and paste then it doesn't works when editor has some content on the component load. see example as below

https://www.useloom.com/share/db119cd699744b21bc11ca445f5d7e71

**Comment by ahrbil** [comment]
for me i was facing this issue when switching to read only 
what I did is instead of passing read-only to the editor I pass it from the state
and I pass the raw content directly from the construction instead of component did mount
![code](https://user-images.githubusercontent.com/16563523/50290791-16ae9f80-046d-11e9-8aa3-f64300ac92b6.png)

i hope this help you

**Comment by ahrbil** [comment]
for me i was facing this issue when switching to read only
what i found is  passing  the raw content directly from the construction instead of component did mount
![code](https://user-images.githubusercontent.com/16563523/50291221-45794580-046e-11e9-9d0d-23e9bab08af1.png)
hope this helps you

**Comment by shobhit-github** [comment]
Thanks buddy, but I fixed it already

**Comment by FilipMessa** [comment]
@shobhit-github May I ask you, how you solved that?
