### ISSUE TITLE
[draft-js-emoji-plugin] Incorrect focus on paste of text containing emoji unicode

### ISSUE THREAD

**Issue by johnsenpeder** [draft-js-plugins/draft-js-plugins#1260]
If you paste text that has emoji unicode somewhere in the middle with no whitespace around it, the editor wrongly sets the focus to just after the last emoji in the pasted text.

This can be replicated on the official example page for the emoji plugin:
https://www.draft-js-plugins.com/plugin/emoji

Try and paste this in the first example:
`wefpokwpeofkpwoekfp👍wepfowk👍peofkwpoekfwe`

**Comment by hero-guo** [comment]
I have the same problem. Is there a solution？

**Comment by johnsenpeder** [comment]
@hero-guo I might try look into this soon if I get the time, I'll report back here with my findings unless someone else beats me :)

**Comment by johnsenpeder** [comment]
Looks like the issue is this: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/index.js#L209 It's forcing the selection to the new editor state selection, which from `attachImmutableEntitiesToEmojis` is now the last unicode converted to an emoji entity.

From initial testing it looks like just getting the current selection: `const currentSelectionState = editorState.getSelection();` before `let newEditorState = attachImmutableEntitiesToEmojis(editorState);` and using that in the `forceSelection` call instead works :thinking: 

cc @hero-guo

**Comment by hero-guo** [comment]
thanks




| |
郭广宇
邮箱：handsamechina@126.com
|

签名由 网易邮箱大师 定制

On 06/18/2019 18:01, Peder Johnsen wrote:

Looks like the issue is this: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/index.js#L209 It's forcing the selection to the new editor state selection, which from attachImmutableEntitiesToEmojis is now the last unicode converted to an emoji entity.

From initial testing it looks like just getting the current selection: const currentSelectionState = editorState.getSelection(); before let newEditorState = attachImmutableEntitiesToEmojis(editorState); and using that in the forceSelection call instead works 🤔

cc @hero-guo

**Comment by hero-guo** [comment]
@johnsenpeder thanks! I am now using `moveFocusToEnd` to solve it in the `onChange` event

**Comment by johnsenpeder** [comment]
Using `moveFocusToEnd` might cause issues if you paste stuff in the middle of the existing content, or even if you just try typing anywhere but at the end? :confused: 

If you do what I mentioned in my comment, it should keep the correct focus no matter where you paste/type stuff

**Comment by sspread** [comment]
@johnsenpeder I just ran into this issue. It is also a problem when programmatically initially focusing on mount when emojis pre-exist in the text. Your solution works. Any reason it shouldn't be a PR? Pretty sure the current implementation is a bug.

**Comment by johnsenpeder** [comment]
@sspread I just haven't had the time to get a PR setup :running_man:
