### ISSUE TITLE
 createHashtagPlugin({ theme: hashtagStyles }); Theme is not working

### ISSUE THREAD

**Issue by varunajmera0** [draft-js-plugins/draft-js-plugins#1265]
I am following same example - https://www.draft-js-plugins.com/plugin/hashtag
but the theme is not applying
codesandbox implementation - 
https://codesandbox.io/s/facebookeditor-u0s1f?fontsize=14

**Comment by gauravsoti1** [comment]
export default (config = {}) => {
  // Styles are overwritten instead of merged as merging causes a lot of confusion.
  //
  // Why? Because when merging a developer needs to know all of the underlying
  // styles which needs a deep dive into the code. Merging also makes it prone to
  // errors when upgrading as basically every styling change would become a major
  // breaking change. 1px of an increased padding can break a whole layout.
  const theme = config.theme ? config.theme : defaultTheme;
  const DecoratedHashtag = props => <Hashtag {...props} theme={theme} />;
  return {
    decorators: [
      {
        strategy: hashtagStrategy,
        component: DecoratedHashtag,
      },
    ],
  };
}
If you check your css import, it will be returning undefined, I am trying to figure out why that's happening.
By default they use linaria lib. If you use css module from this library, your styles would work. 
But this is not a long-term solution. Long-term solution is support for providing classname or javascript styles object.

**Comment by gauravsoti1** [comment]
@varunajmera0 
Currently good solution is to do this: 
Name your css class as HashtagStyles.module.css 
then import it as 
`import hashtagStyles from './HashtagStyles.module.css';
`
then use it as 
`const hashtagPlugin = createHashtagPlugin({
      theme: hashtagStyles
    });`
It would work.
The point is that hashtag plugin needs css module, this approach does that.
You can read create-react-app documentation here: https://create-react-app.dev/docs/adding-a-css-modules-stylesheet
