### ISSUE TITLE
Weekly 1hour slot for a meeting with the team and everyone else who wants to join?

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#140]

**Comment by mxstbr** [comment]
Fixate a time that works for you and then publish it. Don't try to coordinate with all of the collaborators I'm that won't work out.

**Comment by juliankrispel** [comment]
For me personally it's pretty tricky to attend any-time since I have other duties (like kids, and a full time job) and because afternoon PST for example is right in the middle of the few hours of sleep that I get per day.

I think we could coordinate with all of the collaborators, if we use doodle for example, I've set up one [for thursday]((http://doodle.com/poll/my5qwwunxip72pef)), but happy to change the date, or create a new one for a day that works for you @nikgraf
