### ISSUE TITLE
Unexpected autofocus happening

### ISSUE THREAD

**Issue by Sabrinovsky** [draft-js-plugins/draft-js-plugins#2545]
## Environment

Any project with npm/yarn installed.

- @draft-js-plugins/editor version: 4.1.1

## Description

When Editor (@draftjs-plugins/editor) is started, a not desired autofocus happens and any other autofocus in the page does not work.

This autofocus happens whether or not a plugin is installed.

It does not happen on version 4.1.0

## Reproducible Demo

In this app demo it's possible to observe an Input and a Editor.

Note that Input is marked to autofocus, but actually Editor receives the focus.

[codesandbox](https://codesandbox.io/s/jovial-liskov-lpkl5?file=/src/App.js)

[app running](https://lpkl5.csb.app/)

**Comment by Sabrinovsky** [comment]
For some reason it is not happening anymore...

**Comment by Sabrinovsky** [comment]
The focus is happening even if the draftjs is on readOnly:

https://codesandbox.io/s/draftjs-editor-warning-invalid-selection-ofz0y?file=/src/App.js

**Comment by ghifari-ramadhan** [comment]
I got the same result when using the Editor component from '@draft-js-plugins/editor';

Is there any solution?

**Comment by Sabrinovsky** [comment]
> I got the same result when using the Editor component from '@draft-js-plugins/editor';
> 
> Is there any solution?

For now, i suggest you to downgrade to version 4.1.0 @draftjs-plugins/editor

**Comment by laurenz-glueck** [comment]
This bug just cost me two hours of my life 🤯

I have two draft-js-plugins Editor instances in one view and due this autofocus issue they where not accepting initial values... Took me forever until I found out that it is a problem with the draft-js-plugins Editor. Then I found this issue and just downgrade to version 4.1.0 - problem solved (for now).

Would be great if this issue could be fixed as soon as possible. Otherwise **the release of version 4.1.1 should be rolled back**!

FYI: @fxOne (issue is probably caused by changes of #2521 / issue #2469)
