### ISSUE TITLE
Howto dev/test/build custom plugin

### ISSUE THREAD

**Issue by jonathanasquier** [draft-js-plugins/draft-js-plugins#280]
Hi @nikgraf,
I'm really interested in building custom plugins using draft js plugin editor but I'm currently hitting a wall right now... Would you have docs/tips to dev/test/build custom plugins please?

Thanks a lot!

**Comment by nikgraf** [comment]
@jonathanasquier I was planning to write a guide for quite a while, but right now I'm super busy finishing up a project. 

I guess the easiest would be to clone @marcelometal's indepedent plugin repo:
https://github.com/icelab/draft-js-autolist-plugin

Another approach is to this repo and just code in one of the plugins. By running the docs you could test it live. The docs even have hot-reloading.

**Comment by oyeanuj** [comment]
I'd be interested in this as well once you get a chance.

@marcelometal @bkniffler Since both of you have worked on this as well, any chance of making a small guide out of your knowledge? :)

**Comment by jonathanasquier** [comment]
Hi,
So I cloned the draft-js-plugin repo, `npm run build` inside a module and required it in a very simple react app. the build seems to work since the `lib` folder is exactly the same as the one in the npm installed module. All I did was changing the path to the module (the project works when calling the npm installed module of course).
I'm getting errors : 
```
Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.
```
```
Uncaught Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
I'm trying to make a slightly different mention plugin (a few tests where made sucessfully directly in the `node_module` folder).

Any chance I'm missing something?
Thanks!

**Comment by bkniffler** [comment]
@jonathanasquier 
Your first error comes from react, the `suppressContentEditableWarning` doesn't seem to be true, which could be due to an outdated draft-js version or a div with contentEditable = false without the mentioned prop. Are you sure you don't have an outdated, conflicting draft-js version somewhere in your project?

Also the second error might come from a conflicting react version.

`All I did was changing the path to the module (the project works when calling the npm installed module of course)`
What do you mean exactly by changing the path? Could you explain/show in a bit more details? This all really seems like you got problems with your paths/node_modules.


## Very brief explanations
Sorry, I'm a bit short of time, hopes this helps you find a direction!
### Fiddling
I didn't have any problems really. I cloned the whole project, npm install in root and /docs and I just copied one of @nikgraf's modules and replaced the content with what I needed, added the module to the `docs/webpack.config.base.js` file (alias, loaders) and I could use the plugin in the docs to fiddle around.

### Dev
To use it in my own project I got an alias working in my projects webpack.config file:
```jsx
alias: {
  'draft-js-cool-plugin': path.join(__dirname, '..', '..', 'draft-js-plugins', 'draft-js-cool-plugin', 'src')
}
```
Don't forget to include the path in your loaders (babel/css) also, so it can get transpiled. Checkout `docs/webpack.config.base.js` in draft-js-plugins for an example.

### Production
The build scripts that I copied from @nikgraf also worked out of the box for production. I build the plugin and published it to npm.

**Comment by jonathanasquier** [comment]
Okay so I dumbly duplicated a module in the project, added it in the webpack config, and change it in the doc page, it works.
At first I was doing
```import createMentionPlugin, { defaultSuggestionsFilter } from '~/workspace/draft-js-plugins/draft-js-mention-plugin';```
and switched to webpack alias which works fine in my project.

When importing the builded module :
I've still got both my errors, at first I was using draft js 0.7.0, but set it to 0.5.0 (same version as draft-js-plugin master).
When importing the '/src' : getting an unexpected token import (probably due to my failing webpack config, but as long as I can test the module in the draft-js-plugins docs and use the builded module outside, I'm fine...)

**Comment by nikgraf** [comment]
@jonathanasquier does it work for you good enough for now?

**Comment by jonathanasquier** [comment]
I'm still stuck with with the situation in my previous comment but no worries, I going to push an alternate solution for now and will get back to it later
Feel free to close :)

**Comment by nikgraf** [comment]
@jonathanasquier ok, sorry it's a little bit more work than I can scope with right now. I need to take up the task with highest priority & do one by one 😄
