### ISSUE TITLE
DND upload does not keep track of blocks, selection or upload placeholder

### ISSUE THREAD

**Issue by qhenkart** [draft-js-plugins/draft-js-plugins#2849]
## Environment

- @draft-js-plugins/editor version: 4.2
- plugin name and version:

## Description
First off, Thank you for this amazing library. I have one request before I start my bug report. https://github.com/draft-js-plugins/draft-js-plugins/pull/2534 introduced major breaking changes, while it did fix the broken handleUpload, it broke the way we had engineered around it (using addImage to upload) as it completely changed the interaction between these two callbacks. It should have been a major version bumpl

it seems the above PR does not maintain the selection state, so the images do not show up where the cursor was on hover when the file was dropped

It also doesn't seem to keep track of the upload placeholder accurately, It is always offset by 1 so it never deletes.  We are reverting and locking into a previous version

## Reproducible Demo

Here you can see the placeholderblocklist contains the key fpmku, which is at the bottom and not at all where the placeholder is
<img width="929" alt="Screen Shot 2022-06-29 at 20 57 03" src="https://user-images.githubusercontent.com/5798752/176504442-7a6802c8-ed46-4f1c-a4e3-5ee029577255.png">

Here you can see where the placeholder actually is, expanded so you can see the keys match. This will not be deleted and will remain
<img width="795" alt="Screen Shot 2022-06-29 at 20 57 21" src="https://user-images.githubusercontent.com/5798752/176504325-d97b7330-aeb1-4e47-b8d5-c61e2b0687c5.png">

at this point the selection is correct, However you will see that the selection is switched during the broken deletion loop. Then when the editor is set to the new one the selection is changed to the block that was deleted and therefore is always at the end since the selection no longer exists
<img width="1089" alt="Screen Shot 2022-06-29 at 21 00 46" src="https://user-images.githubusercontent.com/5798752/176505174-52babe7e-0bc0-422d-ac4a-76012fa20982.png">

**Comment by fxOne** [comment]
Can you provide a fix?
cc @fdemian

**Comment by fdemian** [comment]
Hi @qhenkart [qhenkart](https://github.com/qhenkart) do you have a code example that reproduces this bug ? 
I don't have much time on my hands RN, but if you have code that reproduces the issue, I'll look into it.

**Comment by alex20465** [comment]
Same issue here, on firefox and chrome not even the image demo plugin works properly on:  https://www.draft-js-plugins.com/plugin/image

Its not a special case but the plugin does not work properly.

**Comment by fdemian** [comment]
Yes, you are right, @[alex20465](https://github.com/alex20465) it does not seem to work on the website.

Looking at the code at a glance, there seem to be other changes apart from the ones from my initial PR. When I created this PR the image upload functionality worked, so my guess is that one of those changes broke something . Later this week I'll take look, since they don't seem like big changes.

**Comment by fdemian** [comment]
@fxOne storybook seems to not be working for me.  Installing all the packages and running `start-storybook -p 6006` the repo does not seem to work. I get the following error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/esm/client/preview'
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/fdemian/projects/draft-js-plugins/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/fdemian/projects/draft-js-plugins/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/fdemian/projects/draft-js-plugins/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve 'react-dom/client' in '/Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/esm/client/preview'
  Parsed request is a module
  using description file: /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/package.json (relative path: ./dist/esm/client/preview)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/esm/client/preview/node_modules doesn't exist or is not a directory
      /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/esm/client/node_modules doesn't exist or is not a directory
      /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/esm/node_modules doesn't exist or is not a directory
      /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/dist/node_modules doesn't exist or is not a directory
      looking for modules in /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/node_modules
        /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/react/node_modules/react-dom doesn't exist
      /Users/fdemian/projects/draft-js-plugins/node_modules/@storybook/node_modules doesn't exist or is not a directory
      /Users/fdemian/projects/draft-js-plugins/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/fdemian/projects/draft-js-plugins/node_modules
        existing directory /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom
          using description file: /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client doesn't exist
              .ts
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client.tsx doesn't exist
              .js
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client.js doesn't exist
              .json
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client.json doesn't exist
              .mjs
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client.mjs doesn't exist
              as directory
                /Users/fdemian/projects/draft-js-plugins/node_modules/react-dom/client doesn't exist
      /Users/fdemian/projects/node_modules doesn't exist or is not a directory
      /Users/fdemian/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by fxOne** [comment]
It seems to be this storybook issue: https://github.com/storybookjs/storybook/issues/18662
Maybe you can try the workaround?

**Comment by fdemian** [comment]
That did the trick.

Image uploading does seem to have problems with the placeholder, but the image uploading itself works perfectly fine on the storybook stories with the current code. Don't know why this does not work on the published site, but that's a different problem (maybe someone with more time than me can take a look at that).

I think I've been able to reproduce the bug. That said, @[qhenkart](https://github.com/qhenkart) if you can record your screen when uploading the picture in order to highlight the bug, that will be really helpful in the debugging the cause of this.

I'll report back when I have more info on this.

**Comment by fdemian** [comment]
Update:  I've started working on this this issue and it seems there are two bugs here: 

A) When uploading a new picture, moving the caret or positioning the image in any place other than a new line causes the image to be uploaded just fine, however the placeholder block ( [Uploading <file name> (100%)] ) is not being removed successfully. This happens because the handling (I.E removal) of the placeholder blocks does not seem to keep track of the position the block was in. Don't remember the problem being in the first version of the plugin, but it is here now.

B) The dnd upload plugin on the DraftJS plugins website is not working. 

I'm currently working on the first one, but have no idea why the second one is happening.

**Comment by alex20465** [comment]
The placeholder block is not deleted because the insertPlaceholder returns the wrong block-key... which results to the wrong deletion.

See here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/drag-n-drop-upload/src/components/insertPlaceholder.ts#L30

What is expected is that the image is dropped always at the END.. but this is not true... once you drop a image in between of the nodes the placeholder can not be deleted.

I will try to provide a fix.

**Comment by fdemian** [comment]
Good thing this is off my hands, because I've been very busy with other things this month. The linked PR seems to solve this.
