### ISSUE TITLE
Create a plugin boilerplate

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#305]
This way people can easily get started and we will see some consistency across plugin repos.

**Comment by adrianmc** [comment]
I like this. To be honest, I still have a hard time grasping the whole portal thing and how it works. I started working on the simple decorator-related plugins because I had the hashtag plugin to learn and copy off of.

I'm also not exactly sure how the "store" works either and what it's for exactly. The only "store" I know is the one used in Redux.

**Comment by nikgraf** [comment]
hehe, yeah the whole store thing is kind of a hack to create a connection between the plugin part connected to the editor to the exported component like MentionSuggestions. 

@jasonphillips also recently pointed out a tricky problem that comes with this technique: https://github.com/draft-js-plugins/draft-js-plugins/issues/311

**Comment by bryanph** [comment]
I think a better API is necessary to create a general usable boilerplate, because different plugins use different strategies to get around the fact of getting the editor state (some use the store, some pass a component instance, etc.) and in my opinion none of them are satisfactory to recommend for people to use.

**Comment by nikgraf** [comment]
@bryanph I'm all ears 😃 any suggestions in terms of better API?

**Comment by bryanph** [comment]
Been mentioning some suggestions in #311

**Comment by nikgraf** [comment]
Just created a guide on how to create a plugin: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/HOW_TO_CREATE_A_PLUGIN.md

Any suggestion for improvement?

**Comment by jplorandi** [comment]
I created [draft-js-base-plugin] for this. I am thinking of creating a second class with error checks and throws so that derived classes are well behaved. As a pattern for creating plugins, I believe it works as a boilerplate.

**Comment by juliankrispel** [comment]
I'm closing this issue, if you think this issue is still relevant please let us know why and we'll consider reopening it. Thank you for contributing ✌️

**Comment by ahtesham-quraish** [comment]
@nikgraf , I am using DraftJs plugin architecture which is awesome thing, I never ever thought about having such architecture which enable us to write very fine and modular code. You guys have done a awesome job. One problem, I am facing is how to connect Redux with plugin, so on Redux state updates, plugin should be called and detects the changes. Please guide me through this.
