### ISSUE TITLE
Version mismatch for wysiwyg plugins in repo vs npm; plus peerDependencies

### ISSUE THREAD

**Issue by wkw** [draft-js-plugins/draft-js-plugins#312]
We are starting a project with @bkniffler's wysiwyg editor plugins. I have a couple questions I'd like to clarify. The versions at [npm](https://www.npmjs.com/~bkniffler) are for the most part all a patch version or two beyond those in the `draft-js-plugins/wysiwyg` branch. However to see what the changes are from repo to npm, I built three of them in the repo then diff'd the `lib` dirs against each other, and found zero changes.

Is there an explanation for that? I'm guessing perhaps `npm version patch` was run and they got published, but the changed `package.json` wasn't committed. 

I'm tentatively planning to `npm link` all the plugins into our project to 1) make it easier to quickly make changes to them, and simplify sending up PRs if there's something useful to give back. And, 2) the peerDependency for

```
"react": ">=0.14.0 || 15.0.0-rc",
"react-dom": ">=0.14.0 || 15.0.0-rc"
```

... is blocking jspm.  We're using react `15.1.0`.
I get this attempting to install any of them.

```
err  Installing npm:draft-js-dnd-plugin@1.0.7, no version match for npm:react-dom@15.0.0-rc
warn Installation changes not saved.
```

So I had to change all the plugins' peerDependencies.

I'll put together a PR with those changes to package.json if you'd like.

**Comment by nikgraf** [comment]
@wkw I didn't even know @bkniffler published them. I plan to spending some time tonight and the next couple days to get them merged in.

**Comment by wkw** [comment]
Humm.. same issue here :-(

https://github.com/belle-ui/decorateComponentWithProps/blob/master/package.json#L26
https://github.com/belle-ui/decorateComponentWithProps/blob/master/package.json#L42

**Comment by jasonphillips** [comment]
My understanding was that his plugins relied on more information being passed from the plugins API (like the entire Editor instance?) -- so I'm pretty sure you couldn't use the published wysiwyg plugins at all against the currently published `draft-plugins-editor`.  Although If these are being merged, I'll be very interested in seeing what additions that makes to the plugin architecture. 

Right now, I've been seeking a couple additions that would help on my plugin:  a way to subscribe directly to editorState changes (since get/setEditorState are essentially passive -- see bottom of discussion on https://github.com/draft-js-plugins/draft-js-plugins/issues/311) and the capability to send a custom blockRenderMap (https://github.com/draft-js-plugins/draft-js-plugins/issues/281). It makes me wonder (...thinking of the wysiwyg plugins that need the entire Editor) whether the series of plugins almost becomes like a series of decorators on top of the Editor, overriding any select features in plugin order.

**Comment by wkw** [comment]
@jasonphillips I've been working backwards from his draftjs-wysiwyg (I hate having to type _wysiwyg_ ! :-) -- my typing stops, and I have to say the words mentally... _wizzy_ would be so much easier). I found it, saw that it gave our project a big head start, then started looking at where the plugins could be found, and that appeared to be here on the `"wizzy"` branch.

Since we are just getting started (still setting up project and dependencies in hopefully a sane, forward-thinking way), I welcome the work that's already been done. One useful tidbit that I had not even considered was his use of embedded D-JS editors [table plugin](https://github.com/draft-js-plugins/draft-js-plugins/tree/wysiwyg/draft-js-table-plugin/src).

Lot of learning ahead for our team, and as this project goes through the summer, I expect I'll be a regular participant here and wherever possible, a contributor. As an aside, we're replacing the WordPress TinyMCE editor with draft-js. The entire frontend of the site is React, WP as the CMS and we needed a restricted Medium-like editor with the addition of a few custom widgets. Still not decided what we will pass from WP to the frontend; D-JS json, or maybe an [AST](https://github.com/icelab/draft-js-ast-exporter). But most likely not HTML.

I'm in the Slack group _@wkw_ if anyone wants to discuss these things further.

**Comment by nikgraf** [comment]
@jasonphillips these are the changes needed. I will try to merge them today or tomorrow and publish a 2.0 beta since it contains breaking changes -> https://github.com/draft-js-plugins/draft-js-plugins/pull/272

Initially @bkniffler used a lot of decorations, but he discovered that this triggers re-mounting of sub-component which led to some issues and he switched to a version where he decorates plugins. I'm not sure if the latest changes were published.

@wkw you are right, @bkniffler started with his editor and then started to port it to the plugin system.
I'm looking forward to your contributions. We have a #draft-js-plugins channel on Slack. Feel free to join or ping there.

**Comment by wkw** [comment]
As I continue to deal with the peerDependencies problem in the plugins and `decorate-component-with-props`, I came across this article this morning: [Dealing with the deprecation of peerDependencies in NPM 3](https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/). I'd like to suggest that as the issue of `">=0.14.0 || 15.0.0-rc"` is dealt with, perhaps those peerDeps should just move to regular `dependencies`. Welcome discussion on this.

**Comment by wkw** [comment]
closing this issue with the final note about pre-release versioning which @nikgraf and I discussed in Slack.
it appears `-beta1` is not correct semver; rather use either: `-beta` or `-beta.0`, `-beta.1`... etc.
Neither of us was certain (and he noted Facebook used `-beta1` on draft) so if anyone else knows with certainty, pls add your knowledge.

**Comment by nikgraf** [comment]
Will switch to beta.2 for the next one 👍
