### ISSUE TITLE
Styling issues due to the autocomplete dropdown not being appended to the body

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#341]
While I am referring to the mention plugin in particular, this issue applies to other plugins that have an autocomplete dropdown. For now, the component is added to the portal, directly in its container element. It introduces a few styling issues:
- positioning the suggestions is a bit tricky (we managed to deal with it just fine but the current implementation is not perfect as it may be positioned out of the screen)
- part of the element may be hidden if its parent has an `overflow: hidden`

That's just two of the main issues but even from a theoretical point of view, those elements are "out of the flow", on top of the rest and depends on the viewport size. It'd make sense to move them as a direct child of the body. The good news is that those components are already instantiated through portals so it should be pretty straight forward.

**Update:** I've been looking into it and it's far from being trivial. I've found nice screenshots showing an example of the issues we can face when not appending the element to the body:

![suggestions overflowing](http://jamesknelson.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-01-at-11.22.40-pm-800x232.png)

Instead of:

![correct behaviour](http://jamesknelson.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-01-at-11.26.04-pm-800x220.png)

The screenshots are taken from an article explaining how to append a React component to the body: [Rendering React components to the document body](http://jamesknelson.com/rendering-react-components-to-the-document-body/). It's from March 2015 so the code is no more relevant but the point is still valid.

**Comment by nikgraf** [comment]
Yep, this is quite tricky. Ideally we would implement smart absolute positioning like http://tether.io

I'm very opposed to render Elements outside of the the JSX where they are placed. This can cause way more trouble with other libs manipulating DOM and unfortunately there are a ton of libs doing a lot of crazy stuff to the DOM 😄 Happy to be convinced otherwise with a great PR, but just from experience I learned to reply with: "Unfortunately we didn't cover your case yet as we haven't had it ourselves. As a first resort I recommend to find a solution without `overflow: hidden`. A PR is very welcome, but currently not my focus."

**Comment by Zhouzi** [comment]
Agreed, I think doing that would be optimal but in the end it's all a matter of if it's worth the effort or not. Right now, given the complexity and time it'd take, I believe it's not worth the value it would bring. So yeah, your reply seems to be the way to go.

That been said, if you're using plugins that blocks you from adding elements to the `<body>`, an `overflow: hidden;` is the last of your concerns 😄
