### ISSUE TITLE
Separate the plugins into its own sub-module

### ISSUE THREAD

**Issue by zacksiri** [draft-js-plugins/draft-js-plugins#368]
I would be nice to do this so we can install npm packages from master branch when PR's are merged.

**Comment by nikgraf** [comment]
@zacksiri can you elaborator on this issue? Do you mean git submodules? How is it related to master? What's the problem you try to solve?

**Comment by zacksiri** [comment]
@nikgraf yes I mean, git sub-modules because when you merge pull request I have to wait for npm package, if you use separate git hub repos I can just call the packages from git repo's master branch.

**Comment by AndrewHamm** [comment]
@nikgraf @zacksiri I just ran into this problem myself. I believe that if each plugin (draft-js-emoji-plugin, draft-js-hashtag-plugin, etc) had their own git repository we could all benefit in several ways.

1.  When contributing to a particular plugin, these commits will go directly to that plugin repository. They will not mix in with the commits of the draft-js-plugins overall changes. For example, I just contributed a change to improve the emoji-plugin, but to do this I had to clone the entire draft-js-plugins repo and commit to the overall project. Why not better abstract it?

2.  Having a separate repo for a plugin would make it easy to use forks as node modules. Now that I have made changes to the emoji-plugin, I want to use it in my project. But since the emoji-plugin is part of the larger repo I cant simply do something like [this](http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb) because then I would get every plugin not just the emoji-plugin. If it were its own repo then I could simply fork it, make changes, use with npm.

**Comment by ismyrnow** [comment]
This would be hugely helpful to me as well. I'm making a bugfix and needing to have two forks: one of the whole project which is needed to open a pull request, and another fork (a copy of a subfolder, really) of just the module I need so I can add it as a dependency to my project without having to publish to npm.

**Comment by nikgraf** [comment]
I believe Lerna is the future for this project. That's maybe something for post 2.0
