### ISSUE TITLE
Publishing and Images/Code/Toolbar

### ISSUE THREAD

**Issue by sandysaders** [draft-js-plugins/draft-js-plugins#382]
Awesome Library and great work to the whole plugins team 👍🏼! I just have a few questions:

1. I'm struggling to figure out how to publish/render the content of the editor say when someone hits submit or create. How do you render the state from the editor to mark up permanently. Best way to store this data in a DB?

2. I'm in need of the images plugin from the repository however there doesn't seem to be any documentation on using this plugin. Did I maybe miss the docs for the image plugin?

3. The Toolbar plugin doesn't have documentation either, how can you extend the toolbar with more options?

3. I tried to find a code plugin to render code snippets with highlighting however I couldn't find it, is that because there isn't an official code plugin or is there a 3rd party plugin from the community?

**Comment by Zhouzi** [comment]
Hey @sandysaders, thanks for the kind words 😄 

> I'm struggling to figure out how to publish/render the content of the editor say when someone hits submit or create. How do you render the state from the editor to mark up permanently. Best way to store this data in a DB?

Transforming the editor's state into a string is done via DraftJS' api so you might be interested by [Data Conversion](https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html). Given the complexity of the data DraftJS is able to deal with, there are a few steps to go through to convert the state to a html version. It should look like this:

```javascript
// convertToRaw is part of DraftJS' api so make sure to import it
// import { convertToRaw } from 'draft-js';

const content = editorState.getCurrentContent();
const rawContent = convertToRaw(content);
// rawContent is now a JavaScript object you can use
// to build out your html string
```

After a quick google search, there are a few projects that seem to handle that for you, e.g: [draft-js-export-html](https://github.com/sstur/draft-js-export-html). Note that I never used it so I don't know if it'd work for you.

Regarding your question **2** and **3**, I am not sure but I think those plugins are still a work in progress, so that's probably why there's no documentation yet.

> I tried to find a code plugin to render code snippets with highlighting however I couldn't find it, is that because there isn't an official code plugin or is there a 3rd party plugin from the community?

draft-js-plugins doesn't have one but it sounds like a great addition so feel free to contribute if that's something you'd be interested by 👍

**Comment by sandysaders** [comment]
@Zhouzi Thank you very much!

**Comment by Zhouzi** [comment]
Your welcome and feel free to ask if you have any questions 😉

**Comment by Zhouzi** [comment]
@sandysaders I thought about it afterwards but if you're just interested by a plain text version, there's a method for that: [ContentState.getPlainText()](https://facebook.github.io/draft-js/docs/api-reference-content-state.html#getplaintext).

**Comment by nikgraf** [comment]
@sandysaders yep, images & toolbar are still work in progress - sorry was quite busy recently, but finding more time to contribute again 😄
