### ISSUE TITLE
Invariant Violation: There should only be one entity range within this removal range

### ISSUE THREAD

**Issue by tianjianchn** [draft-js-plugins/draft-js-plugins#400]
Drag&Drop multiple images will cause `Invariant Violation: There should only be one entity range within this removal range`. Only one image is ok.

Problem is: In [Line 43 of onDropFile.js](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-dnd-plugin/src/modifiers/onDropFile.js#L43), 

``` js
else if (typeof newEditorStateOrBlockType === 'string') {
   state = defaultHandlePlaceholder(state, selection, { ...placeholder, progress: 1 }, newEditorStateOrBlockType);
}
```

The `selection` should be reassigned on next call, which means that we should call `selection = state.getSelection()`

**Comment by kiliwalk** [comment]
And currently, the images inserted order seems to be reversed. Force the new selection will also solve this problem.

After applying this, we may need to comment these codes([L27 in addBlock.js](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-dnd-plugin/src/modifiers/addBlock.js#L27)):
```js
if (isEmptyBlock || selectedFromStart) {
  insertionTargetSelection = targetSelection;
  insertionTargetBlock = afterRemovalContentState;
}
```
to force a new empty text block before the image, otherwise no place to insert a text between the images

**Comment by nikgraf** [comment]
I haven't had time to review the drag & drop plugin code yet. Will do that in the coming months. Feel free to add a PR and I will ask Ben to review it.
