### ISSUE TITLE
Setting myState from the outside after component is mount will drop the decorators

### ISSUE THREAD

**Issue by itajaja** [draft-js-plugins/draft-js-plugins#446]
say you have

``` js
<Editor editorState={this.props.myState} onChange={this.onChange} /> 
```

After the editor is mounting, if the parent component passes down a new state (through the myState props) to the Editor, the Editor will drop all the plugin decorators, since the decorators are set [only during componentWillMount](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L62).

Let me know if the explanation is not clear, and I will create a minimal reproduction on jsbin or similar

**Comment by nikgraf** [comment]
The decorators are bound to the EditorState. This is default Draft.js behaviour and that's why we matched it as well. I was thinking about providing a utility function to re-inject the decorators if you create a new Editor state.

I was thinking about re-injecting the decorators every time, but this would not be Draft.js default behaviour. Does that help?

**Comment by itajaja** [comment]
Hi, thanks for your answer! The difference between vanilla draftjs and draftjs plugins is that the decorators are defined and injected in the same location the state is create, either with `createEmpty` or with `createWithContent`. The decorators in draft-js-plugins are injected as a prop in the component declaration, hence the mismatch. The flow of editor state in draft-js-plugin has a ping-pong behavior because it's something like:

1) I create the state and pass it as a prop to the `Editor`
2) The editor, in `componentWillMount` changes the state, and it passes it back up on the parent component through the onChange prop
3) The parent prop passes it back down to `Editor` with the state prop

This also has the added requirement that an onChange prop is required, even if the Editor is readOnly. I think to better mimic the behavior of vanilla draftjs there should be a patched version, along with the patched editor, of `createEmpty` and `createWithContent`. The downside of it is, of course, that now you have this redundancy where you have provide the plugins both to the state creator functions *and* the Editor.

food for thoughts :)

**Comment by mzbac** [comment]
@itajaja thanks your explanation, I also feel the decorator handling has some issue in current plugin editor..it's worth to find some way to improve it...

**Comment by mxstbr** [comment]
I keep running into this issue where our links and mentions and stuff just disappear randomly.

I think it'd be worth to re-inject the decorators if the previous and the current editor state aren't referentially the same: (pseudo-code)

```JS
componentWillUpdate(next) {
  if (next.editorState !== this.props.editorState) this.setDecorators();
}
```

**Comment by gnestor** [comment]
My temporary solution is to call `componentWillMount()` on my `<Editor>` instance because `componentWillMount` is where all of the decorators are resolved and merged into the editor state. 

I'm calling the following in my container component's `componentWillReceiveProps` so that I can update the editor state in response to next props:

```js
this.setState({ editorState }, () => {
    this.editor.componentWillMount();
});
```

Assuming the following:

```js
<Editor
  editorState={this.state.editorState}
  onChange={this.onChange}
  plugins={plugins}
  ref={element => {
    this.editor = element;
  }}
/>
```

https://github.com/draft-js-plugins/draft-js-plugins/pull/526 attempted to add a `reloadDecorators` method to the `<Editor>` component which accomplishes the end result. However, I think that this *should just work* for users for this library. Apparently, simply resolving the decorators and merging them into the editor state in `componentWillMount` is not enough. However, doing it in `componentWillReceiveProps` is probably too much and I've observed it doing strange things with the cursor.

My specific use case: I have a single page application that lists available docs and allows users to click on a doc to view/edit. When a user loads the app on a doc route, the decorators are all intact and the doc renders correctly. However, if the user loads the app on the doc**s** route or navigates away from a doc route and back to another doc route (essentially, after the initial instance of the doc component in unmounted), many decorators are missing, such as linkify, link, mention, emoji, images, etc.

**Comment by izzappel** [comment]
Is there a reason why you're using `componentWillMount` instead of `componentDidMount`? I am having issues with nested editors. Only the most nested editor gets the decorators. Changing the `componentWillMount` to `componentDidMount` did solve this issue for me.

**Comment by gnestor** [comment]
@izzappel Are you referring to this:

> My temporary solution is to call componentWillMount() on my <Editor> instance because componentWillMount is where all of the decorators are resolved and merged into the editor state.

`componentWillMount` on `Editor` from draft-js-plugins-editor calls `resolveDecorators` and sets the editor state with the decorators: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L58-L63

**Comment by izzappel** [comment]
@gnestor yes exactly

My temporary solution looks very similar:
```
	componentDidMount() {
		this.editor.componentWillMount();
	}
```

Unfortunately I have no other ideas to fix my problem.

**Comment by gnestor** [comment]
Ya, I'm not sure what the solution is, but something like this could work(at https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L65-L77):
 
```js
componentWillReceiveProps(next) {
  const curr = this.props;
  const currDec = curr.editorState.getDecorator();
  const nextDec = next.editorState.getDecorator();

  if (currDec === nextDec) return;
  if (currDec && nextDec && currDec.decorators.size === nextDec.decorators.size) return;
  if (!currDec && nextDec) return;

  let decorator = curr.editorState.getDecorator();
  let editorState = EditorState.set(next.editorState, { decorator });
  if (next.editorState !== this.props.editorState) {
    decorator = resolveDecorators(this.props, this.getEditorState, this.onChange);
    editorState = EditorState.set(this.props.editorState, { decorator });
  }
  this.onChange(editorState);
}
```

**Comment by izzappel** [comment]
Unfortunately this would not work for my situation.
I do not change the state or the decorators at all. But because I have nested editors the inner editor triggers a state update to the outer one and removes the decorators. It's quite hard to explain, what happens.

In my case it would be enough to exchange the `componentWillMount` with `componentDidMount`.
State changes should not be triggered in the `componentWillMount` anyways.

**Comment by David05500** [comment]
> My temporary solution is to call `componentWillMount()` on my `<Editor>` instance because `componentWillMount` is where all of the decorators are resolved and merged into the editor state.
> 
> I'm calling the following in my container component's `componentWillReceiveProps` so that I can update the editor state in response to next props:
> 
> ```js
> this.setState({ editorState }, () => {
>     this.editor.componentWillMount();
> });
> ```
> 
> Assuming the following:
> 
> ```js
> <Editor
>   editorState={this.state.editorState}
>   onChange={this.onChange}
>   plugins={plugins}
>   ref={element => {
>     this.editor = element;
>   }}
> />
> ```
> 
> #526 attempted to add a `reloadDecorators` method to the `<Editor>` component which accomplishes the end result. However, I think that this _should just work_ for users for this library. Apparently, simply resolving the decorators and merging them into the editor state in `componentWillMount` is not enough. However, doing it in `componentWillReceiveProps` is probably too much and I've observed it doing strange things with the cursor.
> 
> My specific use case: I have a single page application that lists available docs and allows users to click on a doc to view/edit. When a user loads the app on a doc route, the decorators are all intact and the doc renders correctly. However, if the user loads the app on the doc**s** route or navigates away from a doc route and back to another doc route (essentially, after the initial instance of the doc component in unmounted), many decorators are missing, such as linkify, link, mention, emoji, images, etc.

Hey my problem is very similar, if not the same. The editor and plugins work fine on the first time a user creates a comment, and then I store the json object of the editorState in a db. On edit of a comment I have managed to set the editorState to what is should be, but non of the plugins or decorators cant not be triggered (@, :, / etc). Ive noticed that you are `this.editor.componentWillMount();` and I want to try this approach, if there is no fix to this since you left the comment, but I am not sure what `this.editor` is in your case?
