### ISSUE TITLE
Trigger suggestions even when preceded by a non-whitespace character

### ISSUE THREAD

**Issue by whathejoe** [draft-js-plugins/draft-js-plugins#544]
Hi everyone,

I've a very specific use case where I need the mention to be triggered when preceded by anything other than a space or a new line. I've read through the code and saw that in order for the trigger to show the mentions it has to be preceded by one of those two and we currently have no option for that.

I'm curious if you're open to turning this into a feature. Also, is there another way that I may have overlooked besides fixing it off a fork?

Cheers!

**Comment by Revln9** [comment]
there is a file called mentionSuggestionsStrategy.js at the draft-js-plugins module directory , you can modify it to match pretty much anything just use the appropriate regex .

for  the regex try something like this  `[^\s]+` 

Hope this helps

**Comment by whathejoe** [comment]
@Revln9 

Yeah, that's where I saw it. I was trying to avoid creating and maintaining my own fork but I guess that's exactly what I'll be doing. Haha

Thanks for replying.

**Comment by prashantagarwal** [comment]
@Revln9 hey, I have a similar requirement, were you able to achieve this. I tried a regex like `(\\s|^|.)` . But its not working.

**Comment by prashantagarwal** [comment]
@Revln9  still no luck.
So let me explain you want I wanted to achieve.

Basically I want user to enter tokens using mentions in url.
eg.

https://abc.com/{{token1}}/{{token2}}/finally

here:
'{' is the mention trigger.
'{{' is the mentionPrefix.
'}}' is the mentionSuffix (support for which I added in my fork)

also I removed the trailing whitespace that was being entered after every mention is inserted.

The only thing left here to do is show popup whenever the mention Trigger is entered and it should not be preceded with whitespace.

**Comment by whathejoe** [comment]
@prashantagarwal 
The answer is definitely someplace else in the plugin. Removing the pre-trigger regex will result to never showing the suggestions and adding to it does nothing. 

Perhaps @nikgraf can point us in the right direction :)

**Comment by Revln9** [comment]
your problem is regex related , so you need to learn regex to solve this properly , here is my guess about the regex that you can use 
`\{(.*?)\}\}*`

you need to double the escape character when you use it in javascript

`\\{(.*?) \\}\\}*`

lastly you need to split it to put the trigger mention inside of it

`(0, _findWithRegex2.default)(new RegExp('\\' + (0, _lodash2.default)(trigger) + ' \\}\\}*', 'g'), contentBlock, callback);`

and the trigger should be `{`

**Comment by nikgraf** [comment]
@Revln9 @whathejoe @prashantagarwal To tackle this issue, I believe the plugin has to be fundamentally different. Instead of using decorators you could run a regex on every selection change and then show an autocomplete dropdown. The code would be way easier and I believe this could eventually even replace the mention plugin.

If any of you would write autocomplete plugin, that would be awesome …
