### ISSUE TITLE
Whats happening with table plugin?

### ISSUE THREAD

**Issue by myyellowshoe** [draft-js-plugins/draft-js-plugins#618]
I noticed the table plugin was moved to legacy. I'd like to implement a table editor in some way. What's on the roadmap for this?

**Comment by gbbr** [comment]
I've also asked this question via various sources, including attempts to email the contributors. Why is it so hard to get a simple answer to this question?

**Comment by gbbr** [comment]
I've also asked this question via various sources, including attempts to email the contributors. Why is it so hard to get a simple answer to this question? /cc @bkniffler

**Comment by bkniffler** [comment]
Hey, sorry for not showing any presence here, I've stopped working with draftjs some time ago (due to frustration with nesting editors, managing block focus and other stuff). I believe contributing a proper table plugin is difficult but not impossible, maybe there is better ways now than when I started working on this stuff, but back in my days draftjs was very simple with its flat document hierarchy, I've had a better experience with slatejs in that specific case.

draft-js-plugins is still a great project, I think the maintainers and users would be very happy to see a working table plugin, so give it a shot @myyellowshoe! Can't say anything about the current roadmap though, maybe @nikgraf knows more.

**Comment by nikgraf** [comment]
@myyellowshoe @gbbr I rewrote most of the plugins to an approach I felt comfortable to maintain. For the table plugin I didn't find the time nor proper architecture to do so. That's why I took it out. It's still in the legacy folder. I would be happy if anyone is willing to pick it up as a separate project.

Does that help?

**Comment by gbbr** [comment]
Thanks for the insight guys. Personally I was just curious why it ended up
in the legacy folder and if it was because the approach was bad/faulty. But
as it seems the reasons is that nobody got to maintain it.

**Comment by nikgraf** [comment]
Exactly, I'm going to close the issue. Trying to slowly clean up the repo 😄

**Comment by export-mike** [comment]
@nikgraf where can I find the "legacy folder" with the last version of draft-js-table-plugin?

**Comment by export-mike** [comment]
FYI I have a table plugin you can use here: yarn add @mikeljames/draft-js-table-plugin its fairly simple it's not a nested editor just text allowed. its fits with the requirements of the project i'm currently working on,

hope its useful for others.

```yarn add @mikeljames/draft-js-table-plugin```

![ezgif-2-db9b5e8116](https://user-images.githubusercontent.com/2983327/34188012-4e3b386e-e588-11e7-82a5-840a0cd0e094.gif)

**Comment by IzaGz** [comment]
@export-mike  how to install it with npm?

**Comment by cupcoder** [comment]
@export-mike Hi, Mike, Do you have plan to open source your plugin? Is there a way to access your source code and make further improvements?

**Comment by export-mike** [comment]
Hi see my forked version it’s on my GitHub

Sorry I can’t link this to you I’m currently in the Philippines with
rubbish internet

**Comment by cupcoder** [comment]
Thanks @export-mike !

**Comment by mengfoobar** [comment]
@export-mike just wondering if you have an example of how to use it? the implementation is exactly what I'm looking for but I'm having problems getting it to work. If you have some time, it'll be incredible :) Thanks!

**Comment by xserber** [comment]
@export-mike +1 for example use it :) 
I only output empty blocks, but there is no table

**Comment by mengfoobar** [comment]
@cupcoder  just wondering, were you able to get @export-mike 's implementation working?

**Comment by cupcoder** [comment]
@mengfoobar Our project requires formatting of table content so we will need a nested editor which is different from what Mike did. But it looks like draft has some serious issues regarding support nested editor in general. We are looking at alternative technologies such as slate for now.

**Comment by export-mike** [comment]
Yeah this plugin is a compromise due to nested editors being a real pain.

I too have since moved to slatejs
