### ISSUE TITLE
Attempting to focus an Editor component on componentDidMount causes all plugins to fail

### ISSUE THREAD

**Issue by rohannair** [draft-js-plugins/draft-js-plugins#628]
If the parent component of the `Editor` tries to `focus` on the `Editor` during `componentDidMount`, no plugins will work.

The issue is reproduced in this repository: https://github.com/rohannair/test-draft-js/ where the `master` branch is properly working but the `cdm_focus_bug` branch is not. This is the diff of the change: https://github.com/rohannair/test-draft-js/pull/1

Thanks to @adrianmcli for helping me figure this out: 🍾

**Comment by adrianmcli** [comment]
Interestingly enough, if you wrap `this.focus()` inside a `setTimeout()`, the problem goes away:

```js
componentDidMount = () => {
  setTimeout(() => {
    this.focus();
  }, 1000);
};
```

**Comment by adrianmcli** [comment]
I've looked into this further, and while I haven't solved the issue yet, I did notice that the Plugins-Editor usually renders twice.

![screen shot 2017-01-03 at 9 42 13 pm](https://cloud.githubusercontent.com/assets/943555/21630256/8b604fe4-d1fd-11e6-95b3-db315bbdfdf5.png)

In the event that `this.focus()` is called (not inside a `setTimeout()`) within `componentDidMount()`, it actually happens after the first render but before the second render.

![screen shot 2017-01-03 at 9 41 31 pm](https://cloud.githubusercontent.com/assets/943555/21630268/9b6b3692-d1fd-11e6-8391-e7f54553e6e3.png)

In the event that `this.focus()` is called inside a `setTimeout()` of 1 second (inside `componentDidMount()`), it happens after the four renders.

![screen shot 2017-01-03 at 9 41 52 pm](https://cloud.githubusercontent.com/assets/943555/21630283/ba0f23ec-d1fd-11e6-8fb9-af700ec8d744.png)

**Comment by adrianmcli** [comment]
Normally, onChange is only called once during mounting of the Editor:

![screen shot 2017-01-03 at 9 51 40 pm](https://cloud.githubusercontent.com/assets/943555/21630413/e8f6d38e-d1fe-11e6-8b89-6b5e235a5583.png)

But when we have `this.focus()` being called `onComponentDidMount()`, it triggers two additional `onChange()` calls before the second `render` happens:

![screen shot 2017-01-03 at 9 53 47 pm](https://cloud.githubusercontent.com/assets/943555/21630438/2d58a9bc-d1ff-11e6-883f-4e0e3a47de43.png)

I believe this to be the heart of the problem.

**Comment by adrianmcli** [comment]
I believe I have been able to identify the problem.

This is what happens normally when the Plugin Editor mounts:

1. Code inside the constructor is run ([L38-L55](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L38-L55)).
2. After that, `componentWillMount()` will run, and finishes by calling `this.onChange()` ([L75](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L75)).
3. At the end of the `this.onChange()` method, `this.props.onChange` is now called at [L100](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L100) (referring to the parent component, i.e. not the Plugin Editor) with an editorState that has all of our plugins ready-to-go.
4. In the parent, it is typical to have an onChange method like this:
  ```js
  onChange = (editorState) => {
    this.setState({
      editorState,
    });
  };
  ```
5. Since `this.setState` is asynchronous, that means we have now primed ourselves for an all-important **second rendering** that will happen at a later time.
6. The **first rendering** will happen now, since `this.props.onChange` has finished executing and we pop back to finish mounting and rendering the Plugin Editor.
7. Sometime later, the **second rendering** happens, and that's when we get all of our plugins.

Note that our editor only gets the plugins when the **second rendering** happens, because it was that specific `editorState` that carried the plugins.

### The Problem

When the Plugin Editor mounts, it builds an editorState from the original one given by the default draft-js editor by adding plugins inside it. And finally it calls the parent's onChange method in order to *set* it. Once this is *set*, then (and only then) our editor has an editorState with plugins inside it.

But the way we *set* it in the parent's onChange method uses `this.setState()` which is asynchronous. That means if we trigger another onChange BEFORE the first all-important `this.setState` finishes, we're going to end up overwriting the editorState with a second one that doesn't have the plugins.

The reason why this second onChange call won't have the plugins is because it's not being triggered by the constructor. It is instead triggered by the original draft-js editor itself. What ends up happening is that we get zero plugins.

### The Solution

At the end of our onChange, if it's the first time we are mounting the Plugin Editor, we should really be setting the editorState synchronously instead of sending it up to the parent and having it set asynchronously.

@nikgraf do you think you can chime in on this? I can make an attempt at a PR later on.

**Comment by paulyoung** [comment]
Can you do `{ editorState: EditorState.forceSelection(editorState) }` instead of `this.focus()`?

**Comment by paulyoung** [comment]
I'm doing this:

```javascript
componentDidMount() {
  window.requestAnimationFrame(() => {
    this.refs.editor.focus();
  });
}
```

**Comment by alexander-zolotykh** [comment]
Are there new solutions?
