### ISSUE TITLE
Once suggestions prop contains an empty list mentions dropdown closes and doesn't reopen

### ISSUE THREAD

**Issue by stevensacks** [draft-js-plugins/draft-js-plugins#633]
The example for remote data uses a JSON file, however, when the data is not cached (and thus near instantaneous lookup) then the suggestions box will not display reliably (more often than not, it does not display). For example, this issue appeared when I switched from a JSON file to Algolia for my mention lookups.

You can easily recreate this by either putting the JSON data for the remote example on to a service like Algolia and loading it that way, or you can use a setTimeout/lodash.delay for every call and set it to around 100-200ms.

**Comment by albertomr86** [comment]
Same problem here!.

I have the following code:

 ```
 render () {
    const { suggestions, onSuggestionsFetchRequested } = this.props;

    return <MentionSuggestions
      onSearchChange={onSuggestionsFetchRequested}
      entryComponent={Entry}
      suggestions={fromJS(this.createMentions(suggestions))} />
  }
```

onSuggestionsFetchRequested will dispatch an async action to search for suggestions. This function is taking around 500ms to complete, and once it is completed my store is updated with the list of suggestions. This value is the one passed as this.props.suggestions.

The problem here is that once the results comes the MentionSuggestions dropdown doesn't show. However if I remove part of the text it shows the current list of suggestions.

Any recommendation on how to solve this?
Thanks!

**Comment by albertomr86** [comment]
Well, fixed!

In my case the problem was that I wasn't playing nice with this condition: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L40

I meant, MentionSuggestions is rendered when is active or has suggestions. When the editor changes it activates the state of MentionSuggestions; and because my "redux store" starts with zero suggestions then the method componentWillReceiveProps closes the dropdown. Once the request fulfills, no suggestions is displayed because the dropdown was closed before.

Here is the flow for better understanding:
1. Editor changed!
2. MentionSuggestions:isActive = true
3. Async request is made.
4. Redux Store suggestions = []
5. MentionSuggestions receive new props.
6. componentWillReceiveProps closes the dropdown because no suggestions.
7. Async request completed, but the dropdown is already closed.

I was able to overcome this issue as follows:
```
shouldComponentUpdate (nextProps, nextState) {
  return this.props.loading && !nextProps.loading;
}
```
where loading is injected as props from the redux store.

Hope this helps!

**Comment by stevensacks** [comment]
I'm glad you figured it out for yourself, but your problem and solution are completely unrelated with this ticket. Your problem was specific to your implementation of passing in suggestions via a prop coming from Redux and your suggestion array being zeroed out in between.

**Comment by stevensacks** [comment]
@nikgraf Any idea when this will be fixed?

**Comment by lorenjohnson** [comment]
👍 Would love to get any timeline on this and/or any feedback from anyone who's came-up with any stop-gap solution...

**Comment by nikgraf** [comment]
@lorenjohnson I would like to tackle this soonish. Right now I'm overwhelmed with answering issues and reviewing PRs. If anyone could look into it and create PR - would be great!

**Comment by juliankrispel** [comment]
Tested this and looking at it @albertomr86's suggestion is right. Whenever we update `mentionSuggestions` with a list that has a length of 0, the popover will close, which will screw up subsequent updates.
