### ISSUE TITLE
WARNING: DraftEntity.get will be deprecated soon!

### ISSUE THREAD

**Issue by bojoyzhou** [draft-js-plugins/draft-js-plugins#676]
How about if DraftEntity.get is deprecated?

I get a warging with the latest draft-js.
```
WARNING: DraftEntity.get will be deprecated soon!
Please use "contentState.getEntity" instead.
```

If so, it seems impossible to get a Entify in blockRendererFn.
How to handle it?

**Comment by jebarjonet** [comment]
The `blockRendererFn` only receives a block as a parameter and returns a component. You should not need the `Entity` in `blockRendererFn`. If you need data in your block in order to render something specific, don't rely on the `Entity` but use [`Modifier.setBlockData`](https://draftjs.org/docs/api-reference-modifier.html#setblockdata) that you can access with [`block.getData()`](https://draftjs.org/docs/api-reference-content-block.html#getdata) instead (data in the block instead of being in the entity).

If you want to access an `Entity`, you have to be in the rendered component returned by `blockRendererFn` where `contentState` will be passed as a prop.

You can access your `Entity` by: 

```javascript
const entity = contentState.getEntity(block.getEntityAt(0))
```

See https://draftjs.org/docs/advanced-topics-block-components.html

**Comment by bojoyzhou** [comment]
@jebarjonet Thanks for the recommendation.

I see some `Entity.get` in **draft-js-plugins**, so I want to know how **draft-js-plugins** will handle this.

**Comment by nikgraf** [comment]
Today I merged a PR upgrading to the latest Draft.js version including the API update. This will be available in Beta10 🙌
