### ISSUE TITLE
[draft-js-mention-plugin]  when I selected one, then press 'Enter' cantnot clear buff

### ISSUE THREAD

**Issue by unrealyan** [draft-js-plugins/draft-js-plugins#687]
![giphy](https://cloud.githubusercontent.com/assets/5870143/23988337/c1f4387e-0a68-11e7-8335-015b0a4bbc7c.gif)

**Comment by abury** [comment]
I'm getting this as well in my code. After a mention, whenever I hit enter it will just put the same mention again and again, and place the cursor at a random position. :(

**Comment by jakegavin** [comment]
I ran into the same issue. I think a potential short term fix is to use `MentionSuggestions`'s `onClose` callback to set the suggestions to an empty list.

Something along the lines of:
```
<MentionSuggestions
  onSearchChange={this.onSearchChange}
  suggestions={this.state.suggestions}
  onClose={() => this.setState({suggestions: fromJS([])})}
/>
```

I _think_ the issue is that suggestions are still getting passed into MentionSuggestions after a selection has happened. 

In the example, the suggestion prop is controlled by the state of the parent component:
```
<MentionSuggestions
  onSearchChange={this.onSearchChange}
  suggestions={this.state.suggestions}
/>
```
Once you select a suggestion, `onMentionSelect` is fired https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L249
which closes the dropdown and sets `MentionSuggestions` `isActive` state to false here https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L290
However the suggestions coming in as in props are still whatever is being passed in by the parent component and that parent component state hasn't been changed.

Then, when you continue typing and `MentionSuggestions` receives the next props, the props still include suggestions from the lsat time suggestions were showing. `this.state.isActive` is `false` which triggers an `openDropdown()` and sets the `handleReturn` callback  https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L44-L46 which results in the weird behavior we're seeing.

The thing I'm not sure about is why the suggestion dropdown isn't visible (so maybe my reasoning behind the issue is incorrect).

I need to wrap up some other stuff but hopefully I'll have a chance to further debug this later today.

**Comment by abury** [comment]
Thanks, @jakegavin, that led me down the right path. To get everything fully working I also had to make sure `MentionSuggestions` started with an empty list. My full code is below:

The below seems to be working perfectly

```javascript
import React, { Component } from 'react'
import { fromJS } from 'immutable'
import { EditorState } from 'draft-js'
import Editor from 'draft-js-plugins-editor'
import 'draft-js-mention-plugin/lib/plugin.css'
import createMentionPlugin, { defaultSuggestionsFilter } from 'draft-js-mention-plugin'
import './editorStyles.scss'
import mentions from './mentions'

const mentionPlugin = createMentionPlugin({
  mentions,
  entityMutability: 'IMMUTABLE',
  mentionPrefix: '@'
})
const { MentionSuggestions } = mentionPlugin
const plugins = [mentionPlugin]

export class SMSMessageEditor extends Component {

  state = {
    editorState: EditorState.createEmpty(),
    suggestions:  fromJS([])
  }

  onChange = (editorState) => {
    this.setState({
      editorState
    })
  }

  onSearchChange = ({ value }) => {
    this.setState({
      suggestions: defaultSuggestionsFilter(value, mentions)
    })
  }

  onAddMention = (mention) => {
    console.log('mention', mention)
  }

  focus = () => {
    this.editor.focus()
  }

  render () {
    return (
      <div className='editor' onClick={this.focus}>
        <Editor
          editorState={this.state.editorState}
          onChange={this.onChange}
          plugins={plugins}
          ref={(element) => { this.editor = element }}
        />
        <MentionSuggestions
          onSearchChange={this.onSearchChange}
          suggestions={this.state.suggestions}
          onAddMention={this.onAddMention}
          onClose={() => this.setState({ ...this, suggestions: fromJS([]) })}
        />
      </div>
    )
  }
}

export default SMSMessageEditor
```

**Comment by nikgraf** [comment]
alright, so ideally we set a default in case no suggestion list is provided, correct? anybody interested to make a PR?

**Comment by thomas88** [comment]
Fixed by https://github.com/draft-js-plugins/draft-js-plugins/pull/871
