### ISSUE TITLE
 Inline-Toolbar & Side-Toolbar configuration options

### ISSUE THREAD

**Issue by mshibl** [draft-js-plugins/draft-js-plugins#708]
Hello, 

In the docs, there a comment about creating a toolbar instance, and that you can pass in a config object. Can you clarify what this config object looks like? Also, Can I pass in custom buttons?

```
// Creates an Instance. At this step, a configuration object can be passed in 
// as an argument.
const sideToolbarPlugin = createSideToolbarPlugin();
```

Thank you,

**Comment by Alex-ray** [comment]
@mshibl it looks like you can pass in a configuration option called structure which will take components.

ref: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-side-toolbar-plugin/src/index.js#L18

On the same note... there is no way to pass props to this component which is a huge problem for me. It would be great to be able to set the structure via an API on the instantiated plugin @nikgraf have you guys thought about this one at all?

**Comment by amannn** [comment]
@Alex-ray Can you provide a use case for the prop you want to pass to the structure? Chances are this is already possible.

E.g. you can do:
```js
const sideToolbarPlugin = createSideToolbarPlugin({
  structure: [props => <TooltipTrigger {...props} specialProp={12} />]
});
```

There's also a package called [decorate-component-with-props](https://www.npmjs.com/package/decorate-component-with-props) on npm that helps with this use case.

**Comment by nikgraf** [comment]
@Alex-ray yeah, a use-case would be super useful - maybe there is a different way already …

**Comment by Alex-ray** [comment]
@amannn @nikgraf , of course!

Here's the problem set Im trying to solve.

The feature is a sidebar component that displays a list of variables generated from a CSV that is uploaded by the user. When clicked that variable is then inserted into the editor as an entity.

The problem arises when these variables change... the variables are based off of a CSV that is uploaded by the user and is passed down via props, which can change at any time.

My hunch is that there may be a more 'react' way to structure plugins so that props follow the same conventions as every other react component.

As a quick hack i've created a global variable that I mutate when the variables change...

Does all that make sense?

**Comment by amannn** [comment]
@Alex-ray Hmm, true!

I can only see that solved through React's context at this point, which is maybe similar to your current workaround. But currently you're restricted to a fixed number of buttons anyway. With PR #729 you'd be able to change the buttons at run time, but you'd still be dependent on a special system like React context or pub/sub or so if you want to change them from the outside, as you can not use regular props.

Currently the `Toolbar` component [is exported already pre-populated with the necessary props](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-side-toolbar-plugin/src/index.js#L40). Maybe it would make sense to use a different HOC there that only sets the predefined props if they are not already present.

Therefore `<SideToolbar />` would still render the way it does currently, but it would allow for `<SideToolbar structure={[DynamicButton1, DynamicButton2]} />` to be rendered next to the editor.

Not sure if this is the best way though. Maybe @nikgraf has more insights.

**Comment by nikgraf** [comment]
hmmm, need to think about it (no brain power anymore after a long day ;) )

**Comment by sidewayskumara** [comment]
Hey not sure if I'm missing something but I think I am having a similar issue regarding passing props into the inline toolbar component. I want to call a redux action when a button in the toolbar is clicked, but because I can't do this: `<InlineToolbar {...props}/>` inside a component that is connected to the redux store (using connect from react-redux) I've also had to expose the input data as a global variable, import the store outside my connected component, and dispatch the action in a callback: 
```
const inlineToolbarPlugin = createInlineToolbarPlugin({
    structure: [props => <MyButton {...props} performAction={() => store.dispatch(myAction(exposedData))} />]
});
```
Wondering if there is a better way I can do this. Thanks!
