### ISSUE TITLE
Could please someone push the packages to npmjs?

### ISSUE THREAD

**Issue by kuatro** [draft-js-plugins/draft-js-plugins#711]

**Comment by stevewillard** [comment]
+1 @nikgraf do you mind publishing beta10 to npm? There's several bug fixes I'd like to take advantage of. Thanks!

**Comment by LachlanStuart** [comment]
It actually was pushed. You can confirm the available versions with `npm view draft-js-plugins-editor versions`.

The issue is that NPM seems to choose the version based on alphabetical sorting of the semver pre-release version, so `2.0.0-beta10` comes right after `2.0.0-beta1` and both are lower than `2.0.0-beta9`. 

The workaround is to specify it the version number exactly: `npm install draft-js-plugins-editor@2.0.0-beta10`.

**Comment by kuatro** [comment]
@LachlanStuart 
```
npm view draft-js-video-plugin versions
[ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '2.0.0-beta.5' ]
```

**Comment by nikgraf** [comment]
@kuatro ouch, seems like if forgot to add that to my publish script

**Comment by nikgraf** [comment]
Just noticed we need to fix the package.json in the video plugin first: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-video-plugin/package.json
