### ISSUE TITLE
Draft JS site example mentions not working in IE11

### ISSUE THREAD

**Issue by 1Jesper1** [draft-js-plugins/draft-js-plugins#734]
The Draft JS mention example does not work in IE11 on [DraftJS site](https://www.draft-js-plugins.com/plugin/mention)

**Comment by nikgraf** [comment]
@1Jesper1 do you have some insights what's going wrong? Any chance you could provide a fix?

**Comment by 1Jesper1** [comment]
Maybe use: 
`import 'babel-polyfill';
// or
import 'es6-shim';`

**Comment by wmill** [comment]
Nope, draft-js-mentions doesn't work in IE11 even with a polyfill. The polyfil will make it load but there are a few breaking bugs.

**Comment by juliankrispel** [comment]
@1Jesper1 @wmill can you provide more info? O_O error logs etc?

**Comment by wmill** [comment]
The problems are in draft-js, two big issues. 

First the implementation they use of setImmediate doesn't work in IE10/11. The setImmediate package will try to use the global setImmediate function if it exists, but the IE10/11 function can only be called as window.setImmediate. You have to call setImmediate.bind(window) and use the result.

Known bug since 2014, no one seems to care.
https://github.com/YuzuJS/setImmediate/issues/35

Next selecting is screwed up in ie11. 

In `src/component/selection/setDraftEditorSelection.js` `addFocusToSelection` is sometimes called with a selection that has no ranges. It's easy to throw in a check to prevent it from crashing, but I don't know why it's happening.

Also in `src/component/contents/DraftEditorLeaf.react.js` using the `forceSelection` prop will cause the component to update without clearing the forceSelection prop so it'll get stuck in a loop of constant updates. You can sort of fix that one by having `shouldComponentUpdate` ignore  `nextProps.forceSelection` on ie11 but that breaks other draft-js features.
