### ISSUE TITLE
EmojiPlugin Wrong focus after EditorState.push 

### ISSUE THREAD

**Issue by lrojas94** [draft-js-plugins/draft-js-plugins#791]
If I do the following, the focus seem to stick to the last `emoji` I placed on the Editor:

1) Write an emoji - e.g: `😋`
2) Set text programically: 
```js
let value = prevText + ' - this will fail'; // prevText contains the emoji 😋
const contentState = ContentState.createFromText(value);
const editorWithContent = EditorState.push(this.state.editorState, contentState, 'insert-characters');
this.setState({
   editorState: editorWithContent,
});
```

This seem to result in the focus staying next to the emoji, even though it should go to the end.
Note that I tried using `moveFocusToEnd`, and it works, but after writing 1 character, it returns next to the emoji.

**Comment by juliankrispel** [comment]
@lrojas94 thanks for reporting this I'll have a look! If you made any progress lmk!

**Comment by jeroenschieven** [comment]
This looks like the same problem as in the [emoji example](https://www.draft-js-plugins.com/plugin/emoji), where after the emoji editor gets rendered a new emoji will be added after latest emoji instead of at the end of the text.

@lrojas94 is this the same problem?

I think after a initial render of the editor the focus should always be set at the end right?

The problem lies at which moment moveSelectionToEnd, from within the draft-js-plugins-editor, is used:

- ComponentWillMount
  - setting up editorstate......
  - this.onChange(moveSelectionToEnd(editorState)) --> setting the focus on the right position
- OnChange
 - plugin.onChange --> In case of the emoji plugin it attaches the immutable entities to the editor state. The focus is being set to the end of the latest entity

I tried and solved the problem by using moveSelectionToEnd only after the plugin.onChange has been called. I'll create a pull request later on to show you my solution.
