### ISSUE TITLE
Multiple Editors each with an Inline Toolbar - Positioning Issues

### ISSUE THREAD

**Issue by AugustKarlstedt** [draft-js-plugins/draft-js-plugins#815]
I have multiple editors on a single page. Each editor has a separate plugins, one of which is the inline toolbar plugin. When selecting text in one editor and then moving on to the next, I sometimes see multiple toolbars appearing over the editors. After inspecting, it seems that one of the editors nearby is updating its toolbar to show over the wrong editor. Gif of issue below.

![draftjspluginissue](https://user-images.githubusercontent.com/9087849/28836288-ec6383f6-76ad-11e7-967a-6e5e524b2956.gif)

**Comment by tention** [comment]
I am facing the same problem here. Anyone has a solution for this? 

This problem will not occur if we click on somewhere else to deactivate the first toolbar, before clicking the second Editor.

**Comment by tention** [comment]
Following PR fixed the problem.

https://github.com/draft-js-plugins/draft-js-plugins/pull/817

**Comment by Kornil** [comment]
Hi @tention sorry I did not see your bug report while submitting the PR.

This bug is related to the inline toolbar persisting out of its own editor, I found the issue in a similar way, just clicking out of the editor the sidebar was following the cursor.
The PR I submitted fixes this problem by making the toolbar checks if the click is inside the editor before it appears.

**Comment by Kornil** [comment]
Follow-up: The PR has been merged, fix should now be available on `@2.0.0-rc4`

**Comment by AugustKarlstedt** [comment]
Thanks @tention and @Kornil!

**Comment by blueyestar** [comment]
I have same problem.
@2.0.1

Only last one editor shows the inline toolbar when text selected.

**Comment by tariqporter** [comment]
Same issue in latest version `3.0.0`

https://stackblitz.com/edit/react-hecgf4
