### ISSUE TITLE
[question] Is it possible to prevent draftjs to cursor over mentions?

### ISSUE THREAD

**Issue by quocble** [draft-js-plugins/draft-js-plugins#843]
After you entering a mention entity, you can move the cursor between the text, and start typing then it breaks the index.  In some case, i assume this could be a feature.  But is it possible to have draft js treat as one cursor position?

**Comment by juliankrispel** [comment]
I think I understand what you're saying but I'm not 100% sure. Mentions are immutable, that means that you can't edit the text within the mentions. This is absolutely intentional and won't change I'm afraid.

If you can tell us more about your usecase however, maybe there's a discussion to be had about whether to create a plugin like this. Feel free to reach out on the [draft-js slack](https://draftjs.herokuapp.com) for more discussion.
