### ISSUE TITLE
Focus plugin re-attaches image entity to a block of text 

### ISSUE THREAD

**Issue by MykolaGolubyev** [draft-js-plugins/draft-js-plugins#902]
## Use-case/Problem

Three blocks:
1. block of text
2. block with an image decorated with focus plugin. 
3. block of text

Select image and press BackSpace. Image with disappear visually. But it is now inside entityRange of the first block of text. 

I have a preview window that takes raw output and prepares a template based on it. That's how I spotted the problem. 

I will try to take a look at the source code of the focus plugin later.

**Comment by voliva** [comment]
@MykolaGolubyev Did you find something? I'm having the exact same issue....

Without taking a deep look, I suspect that has to do with the SelectionState when clicking on the image, because if you press BackSpace, the block gets removed and the content of that block gets appendended to the previous block, while if you press Delete instead, the image is deleted, but the block is kept.
