### ISSUE TITLE
Mention - Not possible initialize mention from plain text

### ISSUE THREAD

**Issue by marlonmleite** [draft-js-plugins/draft-js-plugins#915]
After saving the text with the mention, I have something like this:

> My first mention to **Marta Stewart**

After render my Mention Component with data server, it's not markable the mention people.
It is like normal text:
> My first mention to Marta Stewart

In my `constructor` i use:
```javascript
  constructor(props) {
    super(props)

    const { mentions, value } = props

    this.state = {
      editorState: createEditorStateWithText(value),
      suggestions: mentions
    }

    this.mentionPlugin = createMentionPlugin()
  }
```

**Can not generate mentions from plain text?**

**Comment by vibhu098** [comment]
Do you got any solution to this. ?

**Comment by nicubarbaros** [comment]
Your entityMap object might not be defined, so draft js does not know that there is a mention.

**Comment by goncy** [comment]
@nicubarbaros Can you specify how to do that?

**Comment by tumetus** [comment]
Hello all!

I'm not sure if I understood the question correctly, but in the @marlonmleite 's constructor example above, I assume the editor is initialising the suggestion (=popup that appears when you type @) with **mentions** variable and the editor itself with plain text variable **value**. There is no information about existing mentions and their positions (?).

If you save the editor content with mentions as plain text, there is no way to know where the mention is supposed to be. But if you save the editor content as json using [convertToRaw](https://draftjs.org/docs/api-reference-data-conversion.html) function and then initialise the editor with that json, it is possible because entityMap is saved.

What happens when you add a mention is, there is an object with type = "mention" created to the entityMap. This object will have information about the mention and then in the blocks.entityRanges will have information on what part of the text that entity belongs to. (More about storing draft js editor content [here](http://tuomo.me/how-to-store-draft-js-content-20180404-70/).)

I created a codesandbox which has draft-js-plugins-editor with mentions plugin. When you type something into the editor you can see the editors ContentState as json below the editor. This way you can test out how the ContentState evolves when you type and add mentions to the editor. Here is the link https://codesandbox.io/s/mqvp7mkkrx .

Hopefully this answered what you were looking for or at least cleared things a bit.

**Comment by nicubarbaros** [comment]
@goncy  check my answer #983

**Comment by jangarach** [comment]
Hello, is there any built-in function to solve this problem?

**Comment by jangarach** [comment]
Hello, is there any built-in function to solve this problem?
