### ISSUE TITLE
Decorator strategy is not being called

### ISSUE THREAD

**Issue by stoneG** [draft-js-plugins/draft-js-plugins#955]
I'm trying to write a custom plugin and I'm not seeing any decorator strategies being run. I've tried with my own plugin and also with the `draft-js-linkify-plugin` and neither seem to work. Other plugins that don't use decorators such as `draft-js-inline-toolbar-plugin` seem to work just fine. Not sure if I'm doing something blatantly wrong.

here's a [sandbox](https://codesandbox.io/s/ylk8k3lwj) for the issue.

**Comment by ZhengRaymond** [comment]
#168 

The decorators are being overrode when you add a `componentDidMount`. I had the same issue earlier. Removing `componentDidMount` seems to fix it, although @nikgraf did mention it was fixed in version 1.0...?

For context, the plugin I'm working on, I forked the draft-js-plugins repo, templated my plugin off of nik's Mention plugin, and am running/testing my plugin on the included storybook.

**Comment by stoneG** [comment]
Ahhh, wild. That does seem to fix it, many thanks @ZhengRaymond!
