### ISSUE TITLE
Resetting editor state without losing decorators?

### ISSUE THREAD

**Issue by viridia** [draft-js-plugins/draft-js-plugins#982]
I know this bug has been reported multiple time already, but every one of them has been closed with no clear resolution.

I need to be able to reset the state of the editor - clearing all undo history. Unfortunately, when I do this the mention plugin stops working because all of the decorators go away. I can't use EditorState.push() because that preserves undo history, which I don't want. I've also tried completely destroying and re-creating the editor each time, but have been unable to get that to work - it seems to create more problems than it solves.

I've spend about two days on this, and have tried a dozen different approaches. The past issues give tantalizing hints of possible solutions, but it doesn't look like any of them were ever actually merged.

**Comment by juliankrispel** [comment]
I'd say do one of the following:
1. Clear the undo stack (the editor state is an immutable object, just replace the undo stack (which I suppose is a Map, with an empty map) and you should get the expected behaviour)
2. convert content state to raw and convert it back

**Comment by davidtran** [comment]
Could you give me more details answer ?

**Comment by juliankrispel** [comment]
@davidtran sry rather busy right now but please join the draft js slack and ask there - there are plenty of people who are willing to help I'm sure

**Comment by goodhyun** [comment]
For someone who is still struggling with this. 
Even though modifying the contents is not recommended, it's JS after all. it's the beauty of this language. 

```
import { Map, Stack } from 'immutable';

let editorState = EditorState.push(this.state.editorState, convertFromRaw(nextProps.editorState) , 'remove-range')
editorState._immutable = editorState._immutable.set('undoStack', new Stack()).set('redoStack', new Stack())                            
this.setState({editorState})
```

**Comment by Nat-Reid** [comment]
With pushing editorState I wasn't able to get a perfect solution, because I often ended up forgetting to implement it in every place where I needed to programmatically update editorState
`constructor(props: PropTypes) {
        super(props)

        this.state = { remountKey: 1 }
    }

    // the editor has a bad behavior that makes it lose decorators 
    // if the editor state is reinitialized without remounting
    getDerivedStateFromProps: Function
    static getDerivedStateFromProps(props: PropTypes, state: StateTypes) {
        if (props.editorState && !props.editorState.getDecorator()) {
            return {remountKey: state.remountKey + 1}
        }
        return null
    }
   
  render() {
     return (
        <Editor 
            key={this.state.remountKey}
            // ....
        />
`
I found this hacky solution, but it works pretty well. Whenever your component accidentally loses it's decorators at any time in the app, it just remounts and they get set again. It only forces a remount when they're lost so it's totally performant and doesn't ever fail.

**Comment by rizalrhmn** [comment]
@Nat-Reid hello nat, can you please elaborate this method if using react hook? Because I don't quite understand where to get those props: PropTypes, state: StateTypes.

I'm trying using this : 

const mentionPlugin = createMentionPlugin({mentionPrefix: '@'});
const emojiPlugin = createEmojiPlugin();

const myCustomEditor = ({comment}) => { 

 const [editorState, setEditorState] = useState(EditorState.createEmpty())
 const [remountKey, setRemountKey] = useState(1);  
 const editorEl = useRef(null);  
 const [suggestions, setSuggestions] = useState([]);
  
 const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
 const { MentionSuggestions } = mentionPlugin;
  
 const plugins = [mentionPlugin, emojiPlugin]
 
 useEffect(() => {
    if (editorState && !editorState.getDecorator()) {
      const newValue = remountKey + 1
      setRemountKey(newValue)
    }

  }, [editorState])

useEffect(() => {
   const decorators = _.flattenDeep(plugins.map((plugin) => plugin.decorators));
   const decorator = new CompositeDecorator( decorators.filter((decorator, index) => index !== 1) );

    if (!checkIsJson(comment.content)) {
      setEditorState(EditorState.createWithContent(ContentState.createFromText(comment.content)), decorator);
      return;
    }

    setEditorState(EditorState.createWithContent(
    convertFromRaw(JSON.parse(comment.content)), decorator
    ));
    
  }, [comment])

return(
    <div className={styles.AddCommentContainer}>
      <div className={styles.inputComment}>
        <Form >
              <div>
              <Editor 
                    key={remountKey}
                    editorState={editorState}
                    placeholder="Add new comment..."
                    onChange={onEditorStateChange}
                    plugins={plugins}
                    ref={e => editorEl.current = e}
                    keyBindingFn={keyBindingFn}
                    handleKeyCommand={handleKeyCommand}
                  />
                  <MentionSuggestions
                    onSearchChange={onSearchChange}
                    suggestions={suggestions}
                    onAddMention={onAddMention}
                  />
              </div>
)

}

But I get this error : 

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested

I think in my code, whenever this code executed : 
setEditorState(EditorState.createWithContent(
    convertFromRaw(JSON.parse(comment.content)), decorator
    ));

It force the remountKey to be updated, and then it begin to re-run that code again, and then force remountKey again, and again and again....

Any help would be appreciated!

**Comment by sibelius** [comment]
create plugins inside useMemo

**Comment by rizalrhmn** [comment]
@sibelius can you please elaborate more how to use this useMemo and how it correlated with @Nat-Reid solution?

I try this : 

```
 const plugins = useMemo(() => {
    const mentionPlugin = createMentionPlugin({mentionPrefix: '@'});
    const emojiPlugin = createEmojiPlugin();

    const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
    const { MentionSuggestions } = mentionPlugin;

    return [mentionPlugin, emojiPlugin]
  }, [])
```

but now I get this error : 

`ReferenceError: MentionSuggestions is not defined
`

**Comment by rizalrhmn** [comment]
Try this also, : 

```
const mentionPlugin = createMentionPlugin({mentionPrefix: '@'});
const emojiPlugin = createEmojiPlugin();

const myCustomEditor = ({comment}) => { 

......................

const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
    const { MentionSuggestions } = mentionPlugin;
   
  const plugins = useMemo(() => {
    return [mentionPlugin, emojiPlugin]
  }, [])

.........................
```
Still got same error : 

`Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested`

**Comment by sibelius** [comment]
```jsx
const { plugins, MentionSuggestions } = useMemo(() => {
      const mentionPlugin = createMentionPlugin({
        mentionPrefix: '@',
        mentionComponent: Mention,
      });
      const linkifyPlugin = createLinkifyPlugin();

      return {
        plugins: [linkifyPlugin, mentionPlugin],
        MentionSuggestions: mentionPlugin.MentionSuggestions,
      };
    }, []);
```

**Comment by timuster** [comment]
@rizalrhmn  Were you able to resolve the issue when using hooks? If yes, can you please share your working solution?

**Comment by jpribyl** [comment]
For me the solution was to just wait on `editorState.getDecorator()` to exist in the `useEffect` hook something like:
```ts
  useEffect(() => {
    if (
      // decorator doesn't appear on first render, wait to avoid deleting it
      // before it resolves
      editorState.getDecorator()
    ) {
      setEditorState(markdownToEditorState(initialMarkdown, remarkablePlugins));
    }
  }, [remarkablePlugins]);
```
