### ISSUE TITLE
[draft-js-mention-plugin] How to create a mention entity programatically?

### ISSUE THREAD

**Issue by evansque** [draft-js-plugins/draft-js-plugins#983]
I am trying to load a plain text that has mentions from an API that I have no control of, so there is no way that I can export the editState and store it there.

the mention plugin fails to create a mention entity when the editor state is created from text, how can I create an entity programatically?

**Comment by nicubarbaros** [comment]
UP

**Comment by C1one-38** [comment]
+1 it would be very useful

**Comment by bit-dragon** [comment]
You have to create the mentions manually, I'll upload an snippet later today.

**Comment by nicubarbaros** [comment]
Ok so this [gist file](https://gist.github.com/nicubarbaros/8a35a16dd45065891803bbfa3e451d15) is how I am creating mention entities from text with tags in it.

So for example I am having the text  `Hello @Github` and the tag object will be  {id: 'randoom', name: 'Github'}

Now in order to create the mention tag you have to say to the plugin at which position the mention starts/ends in other words `entity range`, for this I am using the function `getIndicesOf` to get the position of `Github` in the string.

**Comment by mcjlnrtwcz** [comment]
You could try sth like
```js
const stateWithEntity = editorState.getCurrentContent().createEntity(
  'mention',
  'IMMUTABLE',
  {
    mention: {id: 'foobar', name: 'foobar', link: 'https://www.facebook.com/foobar'},
  },
)
const entityKey = stateWithEntity.getLastCreatedEntityKey()
const stateWithText = Modifier.insertText(stateWithEntity, editorState.getSelection(), 'foobar', null, entityKey)
EditorState.push(editorState, stateWithText)
```
