### ISSUE TITLE
[emoji-plugin]: Cannot read property 'unicode' of undefined (Repro-able on demo site)

### ISSUE THREAD

**Issue by icd2k3** [draft-js-plugins/draft-js-plugins#991]
## Use-case/Problem

- Go to: https://www.draft-js-plugins.com/plugin/emoji
- Scroll down to the demo input box
- Type `:one:` and click on the icon in the list (the same problem exists for _some_ other emojis too)
- Observe error  `Cannot read property 'unicode' of undefined`

So far, reproducible with these emojis (will add more as I find 'em):
`:one:`, `:two:`, `:three:`, `:four:`, `:five:`, `:six:`, `:seven:`

**Comment by joshfarrant** [comment]
I've run into the same problem and I just thought I'd update here with what I've discovered so far.

It appears that the character at fault is the following, which will probably just show as a white square.

 ⃣ 

From Emojipedia, the character above is the _Combining Enclosing Keycap_ ([Source](https://emojipedia.org/combining-enclosing-keycap/)).

You can also replicate the issue @icd2k3 described by pasting that character into the first demo (_Simple Emoji Example_) in [the docs](https://www.draft-js-plugins.com/plugin/emoji). Take a look at the console to see the same `Cannot read property 'unicode' of undefined` error. You will not hit the error if you use the second demo on that page, as that avoids the [erroring line](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/components/Emoji/index.js#L19) by using native art.

The issue seems to be that the `<Emoji />` component is being passed that character as the `displayText` when the user enters the emoji `:zero:` through `:seven:` and either clicks the suggestion, or presses _Enter_/_Tab_ to accept the suggestion.

Currently, it's not clear why that character gets set as the `decoratedText` when entering emoji `:zero:` through `:seven:` and not `:eight:` or `:nine:`. The expected behaviour is that the `decoratedText` prop _should_ be set to the corresponding emoji, eg 0️⃣ through 7️⃣.

For the moment, I'm guessing that something unexpected is happening [here](https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorBlock.react.js#L189-L199) in the main draft-js project.

I'm going to contine to look into this and I'll report back if/when I have more info.

**Comment by joshfarrant** [comment]
I've narrowed this down a bit more and opened [an issue](https://github.com/facebook/draft-js/issues/1636) on the main draft-js repo.

Once that issue is resolved, the problematic emoji should start working as expected.
